### ISSUE TITLE
Add external node_modules

### ISSUE THREAD

**Issue by cabaag** [Teradata/covalent-electron#26]
I've included the packages as is written in electron-load, and added the variable into typings but I can't make use of it inside electron.

**Comment by jeremysmartt** [comment]
Hello @cabaag, did you do the following?

1. Add to electron-load.js the requires for the node_module you want to use, for example, if you had a node_module called "some_node_module", then add:
`var some_node_module = require('some_node_module');`

2. Include it in the electron/package.json dependencies.  To note: this is different than the package.json at the top of the source tree.  The package.json
in electron/package.json is for node_modules you want to actually be included in the electron app.  The ones listed in the package.json at the top of the source
tree will not be included in the electron app.  So you would add:
`"dependencies": {
    "some_node_module": "^0.0.1"
  },`

3. Declare this variable in src/typings.d.ts.  This will allow typescript to not complain about the use of the node_module variable. For example:
`declare var some_node_module: any;`

4. Then in your typescript file for your component you should be able to use the node_module directly, for example:
`some_node_module.xyz();`

After those 4 steps you should be able to use an external node_module.

**Comment by jeremysmartt** [comment]
@cabaag I am going to add a section to the ReadMe on these same steps.

**Comment by jeremysmartt** [comment]
Added documentation and merged this PR:
https://github.com/Teradata/covalent-electron/pull/29

Closing this issue.
