### ISSUE TITLE
It is not building incremental

### ISSUE THREAD

**Issue by totalard** [Teradata/covalent-electron#32]
Once a change,, The App need to build all . it takes time and stucks flow

**Comment by jeremysmartt** [comment]
Hello @totalard, there is an open PR that will be merged in soon:
https://github.com/Teradata/covalent-electron/pull/31

This makes it so when you make a change it does not rebuild everything and only takes a matter of seconds to show your change.

**Comment by kyleledbetter** [comment]
Just merged that feature

**Comment by jeremysmartt** [comment]
Fixed with https://github.com/Teradata/covalent-electron/pull/31
