### ISSUE TITLE
Is there any reason why covalent-electron isn't using all of beta.6?

### ISSUE THREAD

**Issue by BrentDietrich** [Teradata/covalent-electron#47]
With the exception of the code-editor, all covalent modules are set to beta.3-2. Is there a particular reason why?

Thanks in advance for the awesome covalent repos!

**Comment by jeremysmartt** [comment]
Hi @BrentDietrich 

Just haven't had a chance to upgrade it yet.  😄  Expect a PR soon now!

**Comment by BrentDietrich** [comment]
Hi @jeremysmartt 

Thanks for quick response!

**Comment by jeremysmartt** [comment]
👍

**Comment by jeremysmartt** [comment]
FYI @BrentDietrich Covalent-Electron has been Upgraded to Covalent 1.0.0-beta.6 via #48
